image: mcr.microsoft.com/dotnet/sdk

stages:
  - build

build:
  stage: build
  script:
    - dotnet build ./AutoRepayment
    - cp AutoRepayment/bin/Debug/netstandard2.1/AutoRepayment.dll AutoRepayment.dll
  artifacts:
    name: "auto-repayment"
    paths:
      - mod.json
      - AutoRepayment.dll
  only:
    - master
