image: mcr.microsoft.com/dotnet/sdk

stages:
  - build

build:
  stage: build
  script:
    - dotnet build ./AutoRepayment
    - mkdir auto-repayment
    - cp mod.json auto-repayment/
    - cp preview.png auto-repayment/
    - cp AutoRepayment/bin/Debug/netstandard2.1/AutoRepayment.dll auto-repayment/
  artifacts:
    name: "auto-repayment"
    paths:
      - auto-repayment
  only:
    - master
