image: mcr.microsoft.com/dotnet/sdk

stages:
  - build

build-project:
  stage: build
  script:
    - dotnet build ./AutoRepayment
  artifacts:
    paths:
      - mod.json
      - AutoRepayment/bin/Debug/netstandard2.1/AutoRepayment.dll
